### ISSUE TITLE
error upon addon install in Blender

### ISSUE THREAD

**Issue by GGDRriedel** [josemarinfarina/SciBlend-Core#2]
Installing the addon in Blender yields 
```Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1302, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2367, in exec_command_iter
    if lock_result_any_failed_with_report(self, self.repo_lock.acquire()):
                                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_utils.py", line 2073, in acquire
    raise Exception("acquire(): cookie doesn't exist! (when it should)")
Exception: acquire(): cookie doesn't exist! (when it should)
```

Blender 4.2

**Comment by GGDRriedel** [comment]
Turns out this needs Admin mode for blender

**Comment by josemarinfarina** [comment]
Thanks for reaching out! Have you already solved this by using Blender 4.2 with administrator privileges?
If not, to help diagnose this issue better, could you please share:
	•	Your operating system version
	•	Whether you’re using Blender from Steam or the official website
	•	The exact steps you followed to install the add-on
If the issue persists after trying with administrator privileges, please provide these details and I’ll be happy to help.
